### ISSUE TITLE
tree view design

### ISSUE THREAD

**Issue by DaWe35** [DaWe35/marstorage#9]
![kép](https://user-images.githubusercontent.com/10603822/99827392-d759c380-2b59-11eb-90e1-936cca55ba9f.png)

**Comment by DanielMozes** [comment]
Fixed by d6a73843c4fa126e4e013c523b26d4e0baa42514

**Comment by DanielMozes** [comment]
Fixed by d6a73843c4fa126e4e013c523b26d4e0baa42514

**Comment by HeroHann** [comment]
Well I still have that Problem:
<img width="708" alt="Screenshot 2020-11-26 at 16 52 17" src="https://user-images.githubusercontent.com/34776833/100371289-d9170180-3007-11eb-97f4-187f781efd12.png">

**Comment by DanielMozes** [comment]
@HeroHann Thank you. Please give me your monitor resolution.

**Comment by HeroHann** [comment]
13,3-inch (2560 × 1600),
BUT Chrome is not full screen.
<img width="1680" alt="Screenshot 2020-11-26 at 18 07 45" src="https://user-images.githubusercontent.com/34776833/100377805-4af44880-3012-11eb-8848-9c25fe6cd9de.png">

**Comment by DaWe35** [comment]
@DanielMozes we can use overflow: none for the parent div
